spring.application.name=quecomo

## PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5432/quecomo_db
spring.datasource.username=adminqc
spring.datasource.password=vFQ4.g51!
spring.datasource.driver-class-name=org.postgresql.Driver

#spring.jpa.properties.hibernate.dialect = org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true

logging.level.root=warn
logging.level.io.github.agutierrezdiaz.quecomo=debug
logging.level.org.hibernate.SQL=debug
